### ISSUE TITLE
Where is the tool?

### ISSUE THREAD

**Issue by shirokovnv** [gomzyakov/shifter#1]
It seems like repo doesn't contain the tool yet (work in progress?)

Can you provide more details about how you planning to automate version upgrade?

Looking forward to contribute to your project.

Thank you!

**Comment by gomzyakov** [comment]
@shirokovnv Hi Kolya!

Yep, work in progress :)

My plan is to take the official "upgrade guide", break it down into many small steps and automatically update everything that is possible.

Technically, the process will be built on Laravel pipelines.

I will be glad to receive comments, suggestions and corrections from you ;)

**Comment by shirokovnv** [comment]
Great! I will close the issue until 2024.
